version: "3"

services: 
    dns1:
        image: nov7/bind9:latest
        hostname: dns-server
        ports:
            - 53:53/udp
            - 53:53/tcp
        volumes:
             - ./bind:/bind-data
        tty: true